Deparweb/Deparweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("Apps.seguridad.urls", namespace="Seguridad")),
    url(r'^constancias/',include("Apps.constancias.urls", namespace="Constancias")),
    url(r'^trabaexpe/',include ("Apps.trabaexpe.urls", namespace="Trabaexpe")),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.*)/$', password_reset_confirm,{'template_name':'seguridad/password_reset_confirm.html'},
     name="password_reset_confirm"),
    url(r'^reset/done', password_reset_complete,{'template_name':'seguridad/password_reset_complete.html'},
     name="password_reset_complete"),
]

Deparweb/Apps/trabaexpe/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from Apps.constancias.models import *

class Trabajador(models.Model):
	cargo = (
		("Analista de Vacaciones","Analista de Vacaciones"),
		("Analista de Jubilacion", "Analista de Jubilacion"),
		("Analista de Seguro Social", "Analista de Seguro Social"),
		("Empleado (a) ","Empleado (a)"),
		("Medico (a) ","Medico (a)"),
		("Obrero (a) ","Obrero (a)"),
	)
	codigo=(
		("0424","0424"),
		("0414","0414"),
		("0426","0426"),
		("0416","0416"),
		("0412","0412"),
		("0257","0257"),
	)
	sexo=(
		("Femenino","Femenino"),
		("Masculino","Masculino"),
	)
	estatus=(
		("Activo","Activo"),
		("Inactivo","Inactivo"),
	)
	cedula = models.IntegerField(unique=True, null=True, blank=True)
	nombre = models.CharField(max_length=30)
	apellido = models.CharField(max_length=30)
	telefono = models.IntegerField(null=True,blank=True)
	cod_tele = models.CharField(max_length=20,choices=codigo)
	sexo = models.CharField(max_length=50, choices=sexo)
	num_ric = models.IntegerField(null=True, blank=True)
	fecha_ingre_publi = models.CharField(max_length=10)
	fecha_ingre_institu = models.CharField(max_length=10)
	cod_rac = models.IntegerField(null=True, blank=True)
	cargos = models.CharField(max_length=50, choices=cargo)
	correo =  models.CharField(max_length=50)
	estat_traba = models.CharField(max_length=50, choices=estatus)
	

	def __str__(self):
		return '%s - %s %s %s' %(self.cedula,self.nombre,self.apellido,self.cargos)

class Expedientes(models.Model):
	cod_expe = models.IntegerField(unique=True, null=True, blank=True)
	titulo = models.BooleanField()
	parti_nacimiento = models.BooleanField()
	evalua_empleado = models.BooleanField()
	evalua_obrero = models.BooleanField()
	evalua_comp = models.BooleanField()
	califi_final = models.BooleanField()
	solici_fide_comiso = models.BooleanField()
	recibo_pago = models.BooleanField()
	regis_censo_pers = models.BooleanField()
	sintesis_curri = models.BooleanField()
	cart_cuncub = models.BooleanField()
	trabajador = models.OneToOneField(Trabajador,on_delete=models.CASCADE)
	desca_trimes = models.BooleanField()
	sueldo = models.IntegerField(null=True, blank=True)
	constancias = models.ForeignKey(Constancias,on_delete=models.CASCADE)
	

	def __str__(self):
		return '%s - %s %s %s' %(self.cedula,self.nombre,self.apellido,self.cargos)

Deparweb/templates/panel/Editfirman.html
{% extends '../base/base.html' %}
{% load static %}
{% block content %}
<div class="row myrow">
	<div class="col s12">
		<div class="card-panel">
			<h4 class="title">Editando Firmante</h4>
			<div class="row">
    			<form class="col s12" method="POST">
    				{% csrf_token %}
    				<div class="row">
        				<div class="input-field col s6">
          					<i class="material-icons prefix">account_circle</i>
                    <input type="text" name="cedu_firm" 
                    value="{{ver_firman.cedu_firm.value}}">
          					<label for="icon_prefix">Cedula</label>
        				</div>
        				<div class="input-field col s6">
          					<i class="material-icons prefix">account_circle</i>
                    <input type="text" name="nomb_firm" value="{{ ver_firman.nomb_firm.value }}">
          					<label for="icon_telephone">Nombre</label>
        				</div>
      				</div>
      				<div class="row">
        				<div class="input-field col s6">
          					<i class="material-icons prefix">account_circle</i>
                     <input type="text" name="apel_firm" value="{{ ver_firman.apel_firm.value }}">
          					<label for="icon_prefix">Apellido</label>
        				</div>
        				<div class="input-field col s6">
          					<i class="material-icons prefix">account_circle</i>
                    <input  type="text" name="cargos1" value="{{ ver_firman.cargos1.value }}">
          					<label for="icon_telephone">Cargos</label>
        				</div>
      				</div>
      				<button class="btn waves-effect waves-light right" type="submit">Guardar
    					<i class="material-icons right">send</i>
  					</button>
  					<a href="{% url 'panelAdmin:Admin' %}" class="btn waves-effect waves-light right">Volver</a>
    			</form>	
			</div>
		</div>
	</div>
</div>

{% endblock %}

Deparweb/templates/panel/Listadodefirmantes.html
{% extends '../base/base.html' %}
{% load static %}
{% block content %}
<!-- Main content -->
<!-- <p>
	Actualmente tenemos registrados:
	{% with total=firman.count %}
		{{total}} firmante{{total|pluralize}}
	{% endwith %}
</p> -->

<div class="row">
	<div class="col s10 m9 l9">
		<h5 class="title">Listado de Firmantes</h5>
	</div>
</div>
<table class="dataTable">
	<thead>
		<tr>
			<td>N°</td>
			<td>Cedula</td>
			<td>Nombre</td>
			<td>Apellido</td>
			<td>Cargo</td>
			<td>Opciones</td>
		</tr>
	</thead>
	{% for dato in firman %}
	<tbody>
		<tr>
			<td>{{dato.id}}</td>
			<td>{{dato.cedu_firm}}</td>
			<td>{{dato.nomb_firm}}</td>
			<td>{{dato.apel_firm}}</td>
			<td>{{dato.cargos1}}</td>
			<td><a href="{% url 'Panel:editar' pk=dato.id %}" class="btn waves-effect waves-light" ><i class="material-icons">create</i></a></td>

		</tr>
		{% empty %}
		<td>No hay registros</td>
	{% endfor %} 
	</tbody>
</table>


{% endblock %}

Deparweb/templates/panel/aggtrabajador.html
{% extends '../base/base.html' %}
{% load staticfiles %}
{% block content %}
<style type="text/css">
  .input-error{
    border-bottom:1px solid red !important;
  }
</style>
<!-- Main content -->
<div class="row">
	<div class="col s12">
		<div class="card-panel">
			<h4 class="title">Nuevo Trabajador</h4>
			<div class="row">
    			<form class="col s12" id="form" role="form" method="POST" name="formulario">
              {% csrf_token %}
               <!-- {{ form.as_p }} --> 
              <div class="row">
                <div class="input-field col s12 ">
                    <i class="material-icons prefix">account_circle</i>
                    <input onblur="validation_aggtrabajador();" type="number" name="cedula" id="id_cedula">
                    <label for="icon_prefix">Cedula</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input type="text" name="nombre">
                    <label for="icon_prefix">Nombre</label>
                </div>
        				<div class="input-field col s6">
          					<i class="material-icons prefix">account_circle</i>
          					<input type="text" name="apellido">
          					<label for="icon_telephone">Apellido</label>
        				</div>
              </div>
              <div class="row">
        				<div class="input-field col s6">
          					<i class="material-icons prefix">contact_phone</i>
                    <select name="cod_tele">
                      {% for x,y in trabajador.fields.cod_tele.choices %}
                      <option value="{{ x }}"{% if trabajador.fields.cod_tele.value == x %} selected{% endif %}>{{ y }}</option>
                      {% endfor %}
                    </select>
          					<label for="icon_prefix">Codigo de telefno</label>
        				</div>
        				<div class="input-field col s6">
          					<i class="material-icons prefix">local_phone</i>
                    <input type="number" name="telefono">
          					<label for="icon_telephone">Telefono</label>
        				</div>
      				</div>
              <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">wc</i>
                    <select name="sexo">
                      {% for x,y in trabajador.fields.sexo.choices %}
                      <option value="{{ x }}"{% if trabajador.fields.sexo.value == x %} selected{% endif %}>{{ y }}</option>
                      {% endfor %}
                    </select>
                    <label for="icon_prefix">Sexo</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">receipt</i>
                    <input type="number" name="num_ric">
                    <label for="icon_telephone">Numero de Ric</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">today</i>
                    <input type="text" name="fecha_ingre_publi">
                     <label for="icon_telephone">Fecha de Ingreso Publicado</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">today</i>
                    <input type="text" name="fecha_ingre_institu">
                    <label for="icon_telephone">Fecha de Ingreso Institucional</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">receipt</i>
                    <input type="number" name="cod_rac">
                     <label for="icon_telephone">Codigo de Rac</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">work</i>
                    <select name="cargos">
                      {% for x,y in trabajador.fields.cargos.choices %}
                      <option value="{{ x }}"{% if trabajador.fields.cargos.value == x %} selected{% endif %}>{{ y }}</option>
                      {% endfor %}
                    </select>
                    <label for="icon_telephone">Cargos</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">money</i>
                    <input type="text" name="sueldo">
                     <label for="icon_telephone">Correo</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">update</i>
                      <select name="estat_traba">
                      {% for x,y in trabajador.fields.estat_traba.choices %}
                      <option value="{{ x }}"{% if trabajador.fields.estat_traba.value == x %} selected{% endif %}>{{ y }}</option>
                      {% endfor %}
                    </select>
                    <label for="icon_telephone">Estatus</label>
                </div>
              </div>
              <button class="btn waves-effect waves-light right" type="submit" name="action">Guardar
                <i class="material-icons right">send</i>
              </button>
              <a href="#" class="btn waves-effect waves-light right">Volver</a>
              
            </div>
    			</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="{% static 'js/myvalidaters.js' %}"></script>
<script type="text/javascript">
  <script type="text/javascript">
jQuery(document).ready(function() {
  $('#form').submit(function(e){
    var next_step = true;
    var cedula = document.getElementById('id_cedula')
    var descripcion = document.getElementById('id_descripcion')
    var contenido = document.getElementById('id_contenido')
    var imagen = document.getElementById('id_imagen')
    console.log(cedula.value)
    //var apellido = document.getElementById('id_last_name')
  if (cedula.value.length <=7){
    $(cedula).addClass('input-error');
    $('.alert1').removeClass('hidden');
    document.getElementById('error').innerHTML="- cedula INVALIDO, INTRODUZCA UN MINIMO DE 3 CARACTERES.";
    return false;
  }

  if (cedula.value.length >=8) {
    $(cedula).removeClass('input-error');
    document.getElementById('error').innerHTML="";
    $('.alert1').addClass('hidden');
    //next_step1 = false;
  }
  // if (descripcion.value.length <3){
  //   $(descripcion).addClass('input-error');
  //   $('.alert2').removeClass('hidden');
  //   document.getElementById('error-d').innerHTML="- DESCRIPCION INVALIDA, INTRODUZCA UN MINIMO DE 3 CARACTERES.";
  //   return false;
  // }
  // if (descripcion.value.length >=3) {
  //   $(descripcion).removeClass('input-error');
  //   document.getElementById('error-d').innerHTML="";
  //   $('.alert2').addClass('hidden');
  //   //next_step1 = false;
  // }

  // if (contenido.value.length <15){
  //   $(contenido).addClass('input-error');
  //   $('.alert3').removeClass('hidden');
  //   document.getElementById('error-c').innerHTML="- CONTENIDO INVALIDO, INTRODUZCA UN MINIMO DE 15 CARACTERES.";
  //   return false;
  // }
  // if (contenido.value.length >=15) {
  //   $(contenido).removeClass('input-error');
  //   document.getElementById('error-c').innerHTML="";
  //   $('.alert3').addClass('hidden');
  //   //next_step1 = false;
  // }
  // if (imagen.value.length <1){
  //   $(imagen).addClass('input-error');
  //   $('.alert5').removeClass('hidden');
  //   document.getElementById('error-i').innerHTML="- IMAGEN INVALIDA, CARGUE UNA IMAGEN.";
  //   return false;
  // }
  // else {
  //   $(imagen).removeClass('input-error');
  //   document.getElementById('error-i').innerHTML="";
  //   $('.alert5').addClass('hidden');
  //   //next_step1 = false;
  // }

    })});
</script>
</script>
{% endblock %}

Deparweb/templates/panel/modals.html
<!-- MODAL DE Ofertas laborales -->

<!-- FINAL DEL MODAL -->

<!-- >>>>>>>>>>>>>>>>>>>>> -->

Deparweb/templates/panel/profile.html
<!-- 	{% extends '../base/base.html' %}
{% load staticfiles %}
{% block content %}

<br />
<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ trabajador_form.as_p }}
  <button type="submit">Save changes</button>
</form>
<p>
{% endblock %} -->

Deparweb/templates/panel/template.html
{% load static %}
{% block content %}
<!-- Main content -->



{% endblock %}